### ISSUE TITLE
Having the "Convergence" skill without having anything in the convergence item list crashes the game

### ISSUE THREAD

**Issue by Foxiallis** [Senior-S/JustLeveling-Fork#16]
As per title. Log is here:

`net.minecraft.ReportedException: Container click
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.gui.screens.Screen.m_96579_(Screen.java:444)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.MouseHandler.m_91530_(MouseHandler.java:89)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.MouseHandler.m_168091_(MouseHandler.java:189)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.util.thread.BlockableEventLoop.execute(BlockableEventLoop.java:102)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.MouseHandler.m_91565_(MouseHandler.java:188)
	at MC-BOOTSTRAP/org.lwjgl.glfw@3.3.1+7/org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at MC-BOOTSTRAP/org.lwjgl@3.3.1+7/org.lwjgl.system.JNI.invokeV(Native Method)
	at MC-BOOTSTRAP/org.lwjgl.glfw@3.3.1+7/org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403)
	at TRANSFORMER/minecraft@1.20.1/com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:201)
	at TRANSFORMER/minecraft@1.20.1/com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:219)
	at TRANSFORMER/minecraft@1.20.1/com.mojang.blaze3d.platform.Window.m_85435_(Window.java:274)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1170)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.main.Main.main(Main.java:218)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at MC-BOOTSTRAP/fmlloader@1.20.1-47.3.5/net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111)
	at MC-BOOTSTRAP/fmlloader@1.20.1-47.3.5/net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99)
	at MC-BOOTSTRAP/fmlloader@1.20.1-47.3.5/net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.run(Launcher.java:108)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.main(Launcher.java:78)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)
Caused by: java.lang.NullPointerException: Cannot invoke "java.util.ArrayList.size()" because the return value of "com.seniors.justlevelingfork.registry.skills.ConvergenceSkill.getItems()" is null
	at TRANSFORMER/justlevelingfork@1.1.5/com.seniors.justlevelingfork.registry.skills.ConvergenceSkill.drop(ConvergenceSkill.java:19)
	at TRANSFORMER/justlevelingfork@1.1.5/com.seniors.justlevelingfork.registry.RegistryCommonEvents.onPlayerCraft(RegistryCommonEvents.java:601)
	at TRANSFORMER/justlevelingfork@1.1.5/com.seniors.justlevelingfork.registry.__RegistryCommonEvents_onPlayerCraft_ItemCraftedEvent.invoke(.dynamic)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
	at TRANSFORMER/forge@47.3.5/net.minecraftforge.event.ForgeEventFactory.firePlayerCraftingEvent(ForgeEventFactory.java:895)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.inventory.ResultSlot.m_5845_(ResultSlot.java:44)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.inventory.ResultSlot.m_142406_(ResultSlot.java:56)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.inventory.AbstractContainerMenu.m_150418_(AbstractContainerMenu.java:418)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.inventory.AbstractContainerMenu.m_150430_(AbstractContainerMenu.java:416)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.inventory.AbstractContainerMenu.m_150399_(AbstractContainerMenu.java:294)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.multiplayer.MultiPlayerGameMode.m_171799_(MultiPlayerGameMode.java:431)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.gui.screens.inventory.AbstractContainerScreen.m_6597_(AbstractContainerScreen.java:536)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.gui.screens.inventory.CraftingScreen.m_6597_(CraftingScreen.java:104)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.gui.screens.inventory.AbstractContainerScreen.m_6375_(AbstractContainerScreen.java:329)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.gui.screens.inventory.CraftingScreen.m_6375_(CraftingScreen.java:93)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.MouseHandler.m_168084_(MouseHandler.java:92)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.gui.screens.Screen.m_96579_(Screen.java:437)
	... 28 more`

**Comment by Foxiallis** [comment]
Also, is convergence not automatic? Why is there a config for it?

**Comment by Senior-S** [comment]
Fixed on 1.1.8.
https://modrinth.com/mod/justleveling-fork/versions
Still under review in CurseForge.
